// Server-only content loaders. All reads come from <app root>/content, which is
// generated by scripts/build-content.mjs. Nothing in this module may be imported
// by client components — it exposes hidden case material (invariant 1).
//
// Lookups are manifest/dir-listing based ONLY: user-supplied ids and slugs are
// never joined into filesystem paths (invariant 3).

import fs from 'node:fs';
import path from 'node:path';
import type { CaseImage, CaseMeta, LandingPage, Manifest, PublicCaseMeta, PublicManifest } from './types';

const CONTENT_DIR = path.join(process.cwd(), 'content');

/**
 * Thrown when the generated content/ directory (or a required file inside it)
 * is missing. The message is safe to surface to the client — it never contains
 * case material.
 */
export class ContentError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ContentError';
  }
}

function readContentFile(...segments: string[]): string {
  const filePath = path.join(CONTENT_DIR, ...segments);
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch {
    // Never name canonical files in errors — their slugs name the hidden
    // diagnosis (invariant 1). Other content paths are filename-derived and
    // spoiler-free, so they can stay in the message for diagnosability.
    const what =
      segments[0] === 'canonical'
        ? 'a canonical note'
        : `content/${segments.join('/')}`;
    throw new ContentError(
      `Server content is not built (missing ${what}). Run "node scripts/build-content.mjs" from the app root.`
    );
  }
}

// ---------------------------------------------------------------------------
// Manifest
// ---------------------------------------------------------------------------

let manifestCache: Manifest | null = null;
let caseMetaById: Map<string, CaseMeta> | null = null;

export function getManifest(): Manifest {
  if (manifestCache) return manifestCache;
  const raw = readContentFile('manifest.json');
  let parsed: Manifest;
  try {
    parsed = JSON.parse(raw) as Manifest;
  } catch {
    throw new ContentError('Server content is corrupt (content/manifest.json is not valid JSON). Re-run "node scripts/build-content.mjs".');
  }
  if (!parsed || !Array.isArray(parsed.cases)) {
    throw new ContentError('Server content is corrupt (content/manifest.json has no cases array). Re-run "node scripts/build-content.mjs".');
  }
  // content/ is regenerated manually (gitignored), so a deploy can pair new code
  // with a manifest built by an older script — fail loudly rather than render
  // empty case codes.
  if (parsed.cases.some((c) => typeof c.caseCode !== 'string' || c.caseCode.length === 0)) {
    throw new ContentError('Server content is stale (manifest cases lack caseCode). Re-run "node scripts/build-content.mjs" and redeploy.');
  }
  // Attach clinical themes from the sidecar (content/themes.json: id -> theme),
  // generated by _index/build_db.py. Optional — absent file just leaves theme undefined.
  try {
    const themes = JSON.parse(readContentFile('themes.json')) as Record<string, string>;
    for (const c of parsed.cases) c.theme = themes[c.id];
  } catch {
    /* themes.json is optional */
  }
  manifestCache = parsed;
  caseMetaById = new Map(parsed.cases.map((c) => [c.id, c]));
  return parsed;
}

export function getCaseMeta(id: string): CaseMeta | undefined {
  if (!caseMetaById) getManifest();
  return caseMetaById!.get(id);
}

// ---------------------------------------------------------------------------
// Public (client-safe) projections
// ---------------------------------------------------------------------------

/**
 * Strip server-only fields before a CaseMeta may leave the server (invariant 1):
 * canonicalSlugs are derived from the case H1 title and name the diagnosis
 * (invariant 4's rationale); `file` is unused by the client.
 */
export function toPublicMeta(meta: CaseMeta): PublicCaseMeta {
  const { canonicalSlugs: _slugs, file: _file, ...pub } = meta;
  return pub;
}

let publicManifestCache: PublicManifest | null = null;

/** The manifest as served to the client — every CaseMeta projected spoiler-safe. */
export function getPublicManifest(): PublicManifest {
  if (publicManifestCache) return publicManifestCache;
  const m = getManifest();
  publicManifestCache = {
    builtAt: m.builtAt,
    caseCount: m.caseCount,
    cases: m.cases.map(toPublicMeta),
  };
  return publicManifestCache;
}

// ---------------------------------------------------------------------------
// Case files
// ---------------------------------------------------------------------------

const caseFullCache = new Map<string, string>();

/** Full case markdown — HIDDEN content, server-side only. */
export function getCaseFull(id: string): string {
  const cached = caseFullCache.get(id);
  if (cached !== undefined) return cached;
  const meta = getCaseMeta(id);
  if (!meta) {
    // ids are validated by callers; keep the message spoiler-free regardless.
    throw new ContentError('Unknown case id.');
  }
  // meta.file comes from the parsed manifest, never from user input (invariant 3).
  const text = readContentFile('cases', meta.file);
  caseFullCache.set(id, text);
  return text;
}

const caseStemCache = new Map<string, string>();

/**
 * The "## Candidate stem" section only (heading prefix-matched, up to the next
 * "## " heading), stripped of the heading line itself. This is the ONLY part of
 * a case file that may reach the client.
 */
/**
 * Enriched case files often end the "## Candidate stem" section with a tutor /
 * recollection note (a blockquote or paragraph of teaching commentary that
 * names the diagnosis). Those notes are examiner material — they stay in the
 * full case file used for the hidden prompt — but must NEVER reach the
 * candidate's door note (invariant 1). Keep this marker list in sync with the
 * identical strip in scripts/build-content.mjs (validation parity).
 */
const SPOILER_NOTE_MARKER = /^\s*(?:>\s*)*[*_([]*\s*(tutor note|tutor's note|examiner note|teaching point|recollection note|synopsis)/i;
const SPOILER_NOTE_HEADING = /^\s*#{3,}\s*[*_]*\s*(tutor note|tutor's note|examiner note|teaching point|recollection note|synopsis)/i;
// Block-level tutor-voice tells (a 503-stem audit found these formulaic leaks):
// "(Communication station: … the candidate must …)" trailing meta paragraphs,
// third-person "the candidate must/should…" commentary (door notes say "you"),
// "for tutor"/"do not volunteer"-style asides, and bracketed recall-
// reconstruction notes ("[… recall … the syndrome — X — is the answer]").
const SPOILER_META_BLOCK = new RegExp(
  [
    '\\b(communication|consultation)[\\w /&+-]{0,40} station\\s*:',
    'the candidate (must|should|is expected|will be)',
    'the framework is|the marking hinges|the marks are (won|in)|marks live',
    'for tutor|do not volunteer|do not read (aloud )?to (the )?candidate|not to be read',
  ].join('|'),
  'i'
);
const SPOILER_RECALL_ASIDE = /^\s*(?:>\s*)*[*_]*\[[^\]]*recall/i;

function stripSpoilerNotes(body: string[]): string[] {
  const out: string[] = [];
  let i = 0;
  while (i < body.length) {
    if (body[i].trim() === '') {
      out.push(body[i]);
      i++;
      continue;
    }
    if (SPOILER_NOTE_HEADING.test(body[i])) {
      // A "### Examiner note" subsection: skip until the next heading (or end).
      i++;
      while (i < body.length && !/^\s*#/.test(body[i])) i++;
      continue;
    }
    // Gather the contiguous block (a blockquote = consecutive ">" lines; a
    // paragraph = lines until the next blank line), then judge it whole.
    const isQuote = /^\s*>/.test(body[i]);
    let j = i;
    while (j < body.length && body[j].trim() !== '' && (!isQuote || /^\s*>/.test(body[j]))) j++;
    const block = body.slice(i, j);
    const spoiler =
      SPOILER_NOTE_MARKER.test(block[0]) ||
      SPOILER_RECALL_ASIDE.test(block[0]) ||
      SPOILER_META_BLOCK.test(block.join('\n'));
    if (!spoiler) out.push(...block);
    i = j;
  }
  return out;
}

/**
 * The stem card renders near-plain text (no markdown engine), so source
 * formatting artifacts must not reach it: unwrap blockquote markers ("> ")
 * and drop horizontal-rule separator lines ("---"). Old source material also
 * embeds ENCOUNTER-TIMING sentences from retired formats ("You have 8 minutes
 * with the patient…", "A warning bell sounds at 6 minutes.") that contradict
 * the authoritative per-classification timing shown in the card header —
 * strip those sentence-by-sentence. A sentence goes only if it carries BOTH a
 * timing mark (N minutes / warning bell) AND a format cue, so clinical
 * durations ("chest pain for 30 minutes", "pulse 112/min") survive.
 * Mirrored in scripts/build-content.mjs so build validation sees the served text.
 */
const TIMING_MARK = /\b\d+\s*(?:\*\*\s*)?min(?:ute)?s?\b|warning bell/i;
const TIMING_CUE =
  /\byou (?:will )?have\b|warning bell|of questions?|\bexaminers?\b|min(?:ute)?s?\s+reading|gather your thoughts|reflection|then discussion|examination, then|warned|stop(?:ped|s)?\s+(?:you\s+)?at|alerts?\s+you/i;
const isTimingText = (s: string) => TIMING_MARK.test(s) && TIMING_CUE.test(s);

function stripTimingFormat(line: string): string {
  // Parentheticals first — bullet labels like "Your task (10 minutes …; stopped at 8):"
  const noParens = line.replace(/\s*\*?\(([^)]*)\)\*?/g, (m, inner: string) => (isTimingText(inner) ? '' : m));
  const sentences = noParens.match(/[^.!?]*[.!?]+["')\]*]*\s*|[^.!?]+$/g);
  if (!sentences) return noParens;
  return sentences
    .filter((s) => !isTimingText(s))
    .join('')
    .replace(/[ \t]{2,}/g, ' ');
}

function presentStemLines(lines: string[]): string[] {
  const out: string[] = [];
  for (const raw of lines) {
    let line = raw.replace(/^\s*(?:>\s*)+/, '');
    if (/^\s*(-{3,}|_{3,}|\*{3,})\s*$/.test(line)) continue;
    line = stripTimingFormat(line);
    out.push(line);
  }
  return out;
}

export function getCaseStem(id: string): string {
  const cached = caseStemCache.get(id);
  if (cached !== undefined) return cached;
  const full = getCaseFull(id);
  const lines = full.split('\n');
  const start = lines.findIndex((l) => l.startsWith('## Candidate stem'));
  if (start === -1) {
    throw new ContentError('Case file is malformed (no "## Candidate stem" section). Re-run "node scripts/build-content.mjs".');
  }
  const body: string[] = [];
  for (let i = start + 1; i < lines.length; i++) {
    if (lines[i].startsWith('## ')) break;
    body.push(lines[i]);
  }
  const stem = presentStemLines(stripSpoilerNotes(body)).join('\n').replace(/\n{3,}/g, '\n\n').trim();
  if (!stem) {
    throw new ContentError('Case file is malformed (empty "## Candidate stem" section). Re-run "node scripts/build-content.mjs".');
  }
  caseStemCache.set(id, stem);
  return stem;
}

// ---------------------------------------------------------------------------
// Canonical notes
// ---------------------------------------------------------------------------

let canonicalSlugSet: Set<string> | null = null;
const canonicalCache = new Map<string, string>();

function getCanonicalSlugSet(): Set<string> {
  if (canonicalSlugSet) return canonicalSlugSet;
  const dir = path.join(CONTENT_DIR, 'canonical');
  let entries: string[];
  try {
    entries = fs.readdirSync(dir);
  } catch {
    throw new ContentError('Server content is not built (missing content/canonical). Run "node scripts/build-content.mjs" from the app root.');
  }
  canonicalSlugSet = new Set(
    entries.filter((f) => f.endsWith('.md')).map((f) => f.slice(0, -'.md'.length))
  );
  return canonicalSlugSet;
}

/**
 * Canonical grounding note by slug. Only slugs present in the canonical dir
 * listing resolve — the slug is never joined into a path unless it is in the
 * listing Set (invariant 3). Returns undefined for anything else.
 */
export function getCanonicalNote(slug: string): string | undefined {
  const cached = canonicalCache.get(slug);
  if (cached !== undefined) return cached;
  if (!getCanonicalSlugSet().has(slug)) return undefined;
  let text: string;
  try {
    text = readContentFile('canonical', `${slug}.md`);
  } catch {
    // The file vanished after the dir-listing Set was cached (e.g. a
    // build-content re-run wiped content/ mid-request). Degrade to "no note"
    // — surfacing this as an error could leak the slug, which names the
    // diagnosis (invariant 1). Callers already skip undefined.
    return undefined;
  }
  canonicalCache.set(slug, text);
  return text;
}

// ---------------------------------------------------------------------------
// Clinical images (server-side map; caseCode -> images)
// ---------------------------------------------------------------------------

let caseImagesCache: Record<string, CaseImage[]> | null = null;

/**
 * Photos available for a case, keyed by the stable caseCode. The map lives in
 * content/case_images.json (generated by build-content.mjs). Absent/empty is the
 * normal no-image case. The mapping is server-only — only a RevealedImage (url +
 * caption) may reach the client, and only through an examiner reveal.
 */
export function getCaseImages(caseCode: string): CaseImage[] {
  if (!caseImagesCache) {
    try {
      caseImagesCache = JSON.parse(readContentFile('case_images.json')) as Record<string, CaseImage[]>;
    } catch {
      caseImagesCache = {}; // sidecar optional — absent means no case has images
    }
  }
  return caseImagesCache[caseCode] ?? [];
}

// ---------------------------------------------------------------------------
// Rubric
// ---------------------------------------------------------------------------

let rubricCache: string | null = null;

export function getRubric(): string {
  if (rubricCache) return rubricCache;
  rubricCache = readContentFile('rubric.md');
  return rubricCache;
}

// ---------------------------------------------------------------------------
// Landing pages (public SEO revision content; content/landing/<slug>.json)
// ---------------------------------------------------------------------------

let landingCache: Map<string, LandingPage> | null = null;

/** Load + validate all landing pages once. Absent dir = no landing pages
 *  (optional feature — the /[slug] route then statically generates nothing). */
function loadLanding(): Map<string, LandingPage> {
  if (landingCache) return landingCache;
  const map = new Map<string, LandingPage>();
  const dir = path.join(CONTENT_DIR, 'landing');
  let files: string[];
  try {
    files = fs.readdirSync(dir).filter((f) => f.endsWith('.json'));
  } catch {
    landingCache = map; // no landing/ dir — feature simply absent
    return map;
  }
  for (const f of files) {
    let page: LandingPage;
    try {
      page = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')) as LandingPage;
    } catch {
      continue; // skip a malformed file rather than fail the whole route tree
    }
    // The slug in the JSON is authoritative (it is the URL); require it and the
    // core render fields, else skip — a half-authored page must not 500 /[slug].
    if (
      page &&
      typeof page.slug === 'string' &&
      page.slug.length > 0 &&
      typeof page.h1 === 'string' &&
      Array.isArray(page.sections)
    ) {
      map.set(page.slug, page);
    }
  }
  landingCache = map;
  return map;
}

/** All landing slugs (sorted) — drives generateStaticParams + the sitemap. */
export function getLandingSlugs(): string[] {
  return [...loadLanding().keys()].sort();
}

/** One landing page by slug, or undefined (→ 404). */
export function getLandingPage(slug: string): LandingPage | undefined {
  return loadLanding().get(slug);
}

/**
 * relatedSlugs a page can actually link to — its declared relatedSlugs
 * intersected with the slugs that exist on disk (drops any dangling target so
 * the rendered internal links never 404).
 */
export function resolveRelated(page: LandingPage): LandingPage[] {
  const all = loadLanding();
  return (page.relatedSlugs ?? [])
    .filter((s) => s !== page.slug && all.has(s))
    .map((s) => all.get(s)!)
    .filter((p, i, arr) => arr.findIndex((q) => q.slug === p.slug) === i);
}
