// Server-only content loaders. All reads come from <app root>/content, which is
// generated by scripts/build-content.mjs. Nothing in this module may be imported
// by client components — it exposes hidden case material (invariant 1).
//
// Lookups are manifest/dir-listing based ONLY: user-supplied ids and slugs are
// never joined into filesystem paths (invariant 3).

import fs from 'node:fs';
import path from 'node:path';
import type { CaseMeta, Manifest, PublicCaseMeta, PublicManifest } from './types';

const CONTENT_DIR = path.join(process.cwd(), 'content');

/**
 * Thrown when the generated content/ directory (or a required file inside it)
 * is missing. The message is safe to surface to the client — it never contains
 * case material.
 */
export class ContentError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ContentError';
  }
}

function readContentFile(...segments: string[]): string {
  const filePath = path.join(CONTENT_DIR, ...segments);
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch {
    // Never name canonical files in errors — their slugs name the hidden
    // diagnosis (invariant 1). Other content paths are filename-derived and
    // spoiler-free, so they can stay in the message for diagnosability.
    const what =
      segments[0] === 'canonical'
        ? 'a canonical note'
        : `content/${segments.join('/')}`;
    throw new ContentError(
      `Server content is not built (missing ${what}). Run "node scripts/build-content.mjs" from the app root.`
    );
  }
}

// ---------------------------------------------------------------------------
// Manifest
// ---------------------------------------------------------------------------

let manifestCache: Manifest | null = null;
let caseMetaById: Map<string, CaseMeta> | null = null;

export function getManifest(): Manifest {
  if (manifestCache) return manifestCache;
  const raw = readContentFile('manifest.json');
  let parsed: Manifest;
  try {
    parsed = JSON.parse(raw) as Manifest;
  } catch {
    throw new ContentError('Server content is corrupt (content/manifest.json is not valid JSON). Re-run "node scripts/build-content.mjs".');
  }
  if (!parsed || !Array.isArray(parsed.cases)) {
    throw new ContentError('Server content is corrupt (content/manifest.json has no cases array). Re-run "node scripts/build-content.mjs".');
  }
  // Attach clinical themes from the sidecar (content/themes.json: id -> theme),
  // generated by _index/build_db.py. Optional — absent file just leaves theme undefined.
  try {
    const themes = JSON.parse(readContentFile('themes.json')) as Record<string, string>;
    for (const c of parsed.cases) c.theme = themes[c.id];
  } catch {
    /* themes.json is optional */
  }
  manifestCache = parsed;
  caseMetaById = new Map(parsed.cases.map((c) => [c.id, c]));
  return parsed;
}

export function getCaseMeta(id: string): CaseMeta | undefined {
  if (!caseMetaById) getManifest();
  return caseMetaById!.get(id);
}

// ---------------------------------------------------------------------------
// Public (client-safe) projections
// ---------------------------------------------------------------------------

/**
 * Strip server-only fields before a CaseMeta may leave the server (invariant 1):
 * canonicalSlugs are derived from the case H1 title and name the diagnosis
 * (invariant 4's rationale); `file` is unused by the client.
 */
export function toPublicMeta(meta: CaseMeta): PublicCaseMeta {
  const { canonicalSlugs: _slugs, file: _file, ...pub } = meta;
  return pub;
}

let publicManifestCache: PublicManifest | null = null;

/** The manifest as served to the client — every CaseMeta projected spoiler-safe. */
export function getPublicManifest(): PublicManifest {
  if (publicManifestCache) return publicManifestCache;
  const m = getManifest();
  publicManifestCache = {
    builtAt: m.builtAt,
    caseCount: m.caseCount,
    cases: m.cases.map(toPublicMeta),
  };
  return publicManifestCache;
}

// ---------------------------------------------------------------------------
// Case files
// ---------------------------------------------------------------------------

const caseFullCache = new Map<string, string>();

/** Full case markdown — HIDDEN content, server-side only. */
export function getCaseFull(id: string): string {
  const cached = caseFullCache.get(id);
  if (cached !== undefined) return cached;
  const meta = getCaseMeta(id);
  if (!meta) {
    // ids are validated by callers; keep the message spoiler-free regardless.
    throw new ContentError('Unknown case id.');
  }
  // meta.file comes from the parsed manifest, never from user input (invariant 3).
  const text = readContentFile('cases', meta.file);
  caseFullCache.set(id, text);
  return text;
}

const caseStemCache = new Map<string, string>();

/**
 * The "## Candidate stem" section only (heading prefix-matched, up to the next
 * "## " heading), stripped of the heading line itself. This is the ONLY part of
 * a case file that may reach the client.
 */
export function getCaseStem(id: string): string {
  const cached = caseStemCache.get(id);
  if (cached !== undefined) return cached;
  const full = getCaseFull(id);
  const lines = full.split('\n');
  const start = lines.findIndex((l) => l.startsWith('## Candidate stem'));
  if (start === -1) {
    throw new ContentError('Case file is malformed (no "## Candidate stem" section). Re-run "node scripts/build-content.mjs".');
  }
  const body: string[] = [];
  for (let i = start + 1; i < lines.length; i++) {
    if (lines[i].startsWith('## ')) break;
    body.push(lines[i]);
  }
  const stem = body.join('\n').trim();
  if (!stem) {
    throw new ContentError('Case file is malformed (empty "## Candidate stem" section). Re-run "node scripts/build-content.mjs".');
  }
  caseStemCache.set(id, stem);
  return stem;
}

// ---------------------------------------------------------------------------
// Canonical notes
// ---------------------------------------------------------------------------

let canonicalSlugSet: Set<string> | null = null;
const canonicalCache = new Map<string, string>();

function getCanonicalSlugSet(): Set<string> {
  if (canonicalSlugSet) return canonicalSlugSet;
  const dir = path.join(CONTENT_DIR, 'canonical');
  let entries: string[];
  try {
    entries = fs.readdirSync(dir);
  } catch {
    throw new ContentError('Server content is not built (missing content/canonical). Run "node scripts/build-content.mjs" from the app root.');
  }
  canonicalSlugSet = new Set(
    entries.filter((f) => f.endsWith('.md')).map((f) => f.slice(0, -'.md'.length))
  );
  return canonicalSlugSet;
}

/**
 * Canonical grounding note by slug. Only slugs present in the canonical dir
 * listing resolve — the slug is never joined into a path unless it is in the
 * listing Set (invariant 3). Returns undefined for anything else.
 */
export function getCanonicalNote(slug: string): string | undefined {
  const cached = canonicalCache.get(slug);
  if (cached !== undefined) return cached;
  if (!getCanonicalSlugSet().has(slug)) return undefined;
  let text: string;
  try {
    text = readContentFile('canonical', `${slug}.md`);
  } catch {
    // The file vanished after the dir-listing Set was cached (e.g. a
    // build-content re-run wiped content/ mid-request). Degrade to "no note"
    // — surfacing this as an error could leak the slug, which names the
    // diagnosis (invariant 1). Callers already skip undefined.
    return undefined;
  }
  canonicalCache.set(slug, text);
  return text;
}

// ---------------------------------------------------------------------------
// Rubric
// ---------------------------------------------------------------------------

let rubricCache: string | null = null;

export function getRubric(): string {
  if (rubricCache) return rubricCache;
  rubricCache = readContentFile('rubric.md');
  return rubricCache;
}
